export const COLORS = {
  PRIMARY_BACKGROUND: "#131519",
  SECONDARY_BACKGROUND: "#1f1f21",
  PRIMARY_TEXT: "#FFFFFF",
  PRIMARY_ACTIVE_BUTTON: "#005bf0",
  ICON_WHITE: "#FFFFFF",
  TEXT_WHITE: "#FFFFFF",
  SUCCESS: "#4CAF50",
  ERROR: "#dc143c",
  PRIMARY_BORDER: "#808080",
};
