import { palette } from '@/theme/palette';

export const colors = {
  background: palette.neutral50,
  foreground: palette.neutral900,
  surface: palette.neutral700,
  surfaceForeground: palette.neutral100,
  muted: palette.neutral200,
  mutedForeground: palette.neutral600,
  primary: palette.neutral900,
  primaryForeground: palette.neutral50,
  secondary: palette.neutral100,
  secondaryForeground: palette.neutral900,
  accentPrimary: palette.yellow300,
  accentForeground: palette.neutral900,
  destructiveForeground: palette.red500,
  borderHard: palette.neutral900,
  input: palette.neutral600,
  borderSoft: palette.neutral700,
  accentSecondary: palette.violet500,
  accentTertiary: palette.neutral900,
  accentQuaternary: palette.orange600,
  accentQuinary: palette.pink600,
  primaryHover: palette.neutral800,
  secondaryHover: palette.neutral200,
  outline: palette.neutral100,
  ghostHover: palette.neutral100,
  ghostForeground: palette.neutral900,
  ringError: palette.red300,
  destructiveBorder: palette.red500,
  accentPrimaryHover: palette.yellow400,
  ring: palette.neutral300,
  accentSecondaryActive: palette.violet400,
  destructiveBackground: palette.red100,
  accentSenary: palette.olive600,
  accentSenaryHover: palette.olive500,
};
